" This must be first, because it changes other options as side effect
set nocompatible
set paste

" Pathogen plugin manager setup
execute pathogen#infect()
syntax on
filetype plugin indent on

" Vim customizations
set wrap                        " wrap lines
set tabstop=4                   " a tab is four spaces
set softtabstop=4               " when hitting <BS>, pretend like a tab is removed, even if spaces
set expandtab                   " expand tabs by default (overloadable per file type later)
set shiftwidth=4                " number of spaces to use for autoindenting
set number                      " always show line numbers
set showmatch                   " set show matching parenthesis
set ignorecase                  " ignore case when searching
set scrolloff=1                 " keep 4 lines off the edges of the screen when scrolling
set hlsearch                    " highlight search terms
set incsearch                   " show search matches as you type
set lazyredraw                  " don't update the display while executing macros
set laststatus=2                " tell VIM to always put a status line in, even if there is only one window
set cmdheight=1                 " use a status bar that is 2 rows high
set history=1000                " remember more commands and search history
set undolevels=1000             " use many muchos levels of undo
set cursorline                  " underline the current line, for quick orientation
set ttimeoutlen=10              " Make Esc work faster
set noshowmode                  " -- INSERT -- wont be displayed in the vim status
set nocscopeverbose

" Vim theme setup
set background=dark
"colorscheme oceanicNext
colorscheme Tomorrow-Night-Bright

" Vim Airline customizations
let g:airline_theme='dark'
let g:airline#extensions#whitespace#enabled = 0

" FZF setup
set rtp+=~/.fzf